/*	CANADA ROBERT BORDEN | LOADING INFO		*/
INSERT INTO	LoadingInfo 
			(LeaderType,							BackgroundImage,									ForegroundImage,										PlayDawnOfManAudio)
	VALUES	('LEADER_CANADA_ROBERT_BORDEN',			'LEADER_CANADA_ROBERT_BORDEN_BACKGROUND',			'LEADER_CANADA_ROBERT_BORDEN_NEUTRAL',				0);

/*	CANADA ROBERT BORDEN | DIPLOMACY SCREEN	*/
INSERT INTO DiplomacyInfo
			(Type,									BackgroundImage)
	VALUES	('LEADER_CANADA_ROBERT_BORDEN',			'LEADER_CANADA_ROBERT_BORDEN_BACKGROUND');